export const config = (): any => ({
  database: {
    type: 'mysql',
    host: 'localhost',
    port: 3306,
    username: 'root',
    password: 'Jayrajkumar@123',
    database: 'rss_feed_data',
    synchronize: true,
    logging: true,
    entities: ['./modules/**/*.entity.ts'],
    autoLoadEntities: true,
    keepConnectionAlive: true,
  },
  // database: {
  //   type: 'mysql',
  //   host: process.env.DB_HOST,
  //   port: 3306,
  //   username: process.env.DB_USERNAME,
  //   password: process.env.DB_PASSWORD,
  //   database: process.env.DB_DATABASE,
  //   synchronize: true,
  //   logging: true,
  //   entities: ['./modules/**/*.entity.ts'],
  //   autoLoadEntities: true,
  //   keepConnectionAlive: true,
  // },
});
